import { PatientListTableDataItem } from '../../../../ui/organisms/PatientListTable/types';

export const listData: PatientListTableDataItem[] = [
  {
    id: '0',
    name: 'John Smith',
    age: '34',
    diagnosis: 'Fracture ribs',
    period: '4 hours',
    triageCategory: 'Skeletal trauma',
    status: 'amber',
  },
  {
    id: '1',
    name: 'Alice Johnson',
    age: '45',
    diagnosis: 'Sprained wrist',
    period: '2 hours',
    triageCategory: 'Orthopedic injury',
    status: 'green',
  },
  {
    id: '2',
    name: 'Bob Miller',
    age: '28',
    diagnosis: 'Headache',
    period: '1 hour',
    triageCategory: 'General illness',
    status: 'red',
  },
  {
    id: '3',
    name: 'Eva Davis',
    age: '50',
    diagnosis: 'Influenza',
    period: '3 hours',
    triageCategory: 'Respiratory illness',
    status: 'green',
  },
  {
    id: '4',
    name: 'David Wilson',
    age: '60',
    diagnosis: 'Hypertension',
    period: '5 hours',
    triageCategory: 'Cardiovascular condition',
    status: 'amber',
  },
  {
    id: '5',
    name: 'Sophie Brown',
    age: '22',
    diagnosis: 'Allergic reaction',
    period: '1 hour',
    triageCategory: 'Allergy',
    status: 'green',
  },
  {
    id: '6',
    name: 'Michael Jones',
    age: '40',
    diagnosis: 'Burn injury',
    period: '3 hours',
    triageCategory: 'Burns',
    status: 'red',
  },
  {
    id: '7',
    name: 'Grace Taylor',
    age: '35',
    diagnosis: 'Migraine',
    period: '2 hours',
    triageCategory: 'Neurological disorder',
    status: 'amber',
  },
  {
    id: '8',
    name: 'Daniel Clark',
    age: '55',
    diagnosis: 'Pneumonia',
    period: '4 hours',
    triageCategory: 'Respiratory infection',
    status: 'green',
  },
  {
    id: '9',
    name: 'Lily Moore',
    age: '30',
    diagnosis: 'Broken nose',
    period: '1 hour',
    triageCategory: 'Facial trauma',
    status: 'red',
  },
  {
    id: '10',
    name: 'Ryan Walker',
    age: '25',
    diagnosis: 'Dehydration',
    period: '5 hours',
    triageCategory: 'Fluid imbalance',
    status: 'green',
  },
  {
    id: '11',
    name: 'Emma Carter',
    age: '48',
    diagnosis: 'Gastroenteritis',
    period: '2 hours',
    triageCategory: 'Gastrointestinal issue',
    status: 'amber',
  },
  {
    id: '12',
    name: 'Matthew Harris',
    age: '37',
    diagnosis: 'Kidney stones',
    period: '4 hours',
    triageCategory: 'Renal condition',
    status: 'green',
  },
  {
    id: '13',
    name: 'Olivia Turner',
    age: '27',
    diagnosis: 'Anxiety',
    period: '1 hour',
    triageCategory: 'Mental health',
    status: 'amber',
  },
  {
    id: '14',
    name: 'Christopher Smith',
    age: '32',
    diagnosis: 'Asthma',
    period: '3 hours',
    triageCategory: 'Respiratory condition',
    status: 'red',
  },
  {
    id: '15',
    name: 'Isabella Robinson',
    age: '39',
    diagnosis: 'Diabetes',
    period: '6 hours',
    triageCategory: 'Metabolic disorder',
    status: 'green',
  },
  {
    id: '16',
    name: 'Nathan Allen',
    age: '42',
    diagnosis: 'Back pain',
    period: '2 hours',
    triageCategory: 'Musculoskeletal issue',
    status: 'amber',
  },
  {
    id: '17',
    name: 'Ava Lewis',
    age: '31',
    diagnosis: 'Food poisoning',
    period: '1 hour',
    triageCategory: 'Digestive issue',
    status: 'green',
  },
  {
    id: '18',
    name: 'Tyler White',
    age: '36',
    diagnosis: 'Chest pain',
    period: '3 hours',
    triageCategory: 'Cardiac condition',
    status: 'red',
  },
  {
    id: '19',
    name: 'Sofia Scott',
    age: '29',
    diagnosis: 'Ear infection',
    period: '5 hours',
    triageCategory: 'Ear, Nose, Throat issue',
    status: 'green',
  },
  {
    id: '20',
    name: 'Logan Hall',
    age: '44',
    diagnosis: 'Sprained knee',
    period: '4 hours',
    triageCategory: 'Orthopedic injury',
    status: 'amber',
  },
  {
    id: '21',
    name: 'Olivia White',
    age: '42',
    diagnosis: 'Fractured leg',
    period: '6 hours',
    triageCategory: 'Skeletal trauma',
    status: 'red',
  },
];
